### ISSUE TITLE
Descarga no valida.

### ISSUE THREAD

**Issue by uyfede** [i-nis/garmin-osm#1]
Hola Martin disculpa el uso de este medio; es que no encontré otro, no es un error en los script en si, sino que no puedo descargar nada desde tu cuenta de Dropbox la misma dice que superaste el limite de ancho de banda. Muchas gracias.

**Comment by mggimenez** [comment]
Hola, muchas gracias por reportar el problema. Pido disculpas por tardar en atender el pedido y aprovecho para comentar que es el lugar adecuado para reportar problemas. 

Dada la limitación  mencionada ya no se utilizará más Dropbox, en su lugar utilizaremos uno de nuestros servidores:

http://www.i-nis.com.ar/osm/garmin

O alternativamente desde la réplica (cortesía de Fernando Toledo):

http://osm-garmin.bbs.docksud.com.ar
