### ISSUE TITLE
mirror

### ISSUE THREAD

**Issue by ftoledo** [i-nis/garmin-osm#2]
Hola Martin, yo tengo un mirror de los mapas, pero hace rato que no se actualizan.
Me habías pasado para hacerlo via rsync a rsync://rsync.i-nis.com.ar/garmin-osm
Si ahora está todo en github. Puedo redireccionarlo para aca si te parece.
Gracias!

**Comment by mggimenez** [comment]
Hola Fernando!

No, los mapas no están en GitHub, van a seguir replicandose vía rsync con la misma URL. Esta noche debería replicarse todo sin problemas.

**Comment by mggimenez** [comment]
Se verificaron las URLs en https://wiki.openstreetmap.org/wiki/ES:Wikiproyecto_Argentina y las descargas de los servidores de réplica.
