### ISSUE TITLE
Actualización

### ISSUE THREAD

**Issue by ignaciolep** [i-nis/garmin-osm#4]
Hola, Les aviso que la última actualización en https://www.i-nis.com.ar/osm/garmin es del 31-12-2019. Evidentemente el proceso dejó de correr desde entonces.

**Comment by mggimenez** [comment]
El proceso se ejecuta manualmente y debido a algunos problemas en todo este tiempo no ha podido ser ejecutado. En el día de ayer se ha generado un nuevo mapa que ya está disponible en https://www.i-nis.com.ar/osm/garmin.
